### ISSUE TITLE
Theme variables (tabbed) not taking effect

### ISSUE THREAD

**Issue by M1ndo** [BlingCorp/bling#104]
i have this issue within in tabbed layout theme variables don't work and it results into default theme. .
i'm not sure whats causing this issue , can anyone relate to it or have a fix ?
this is what is in my theme.lua .
```
theme.tabbed_spawn_in_tab = false
theme.tabbar_ontop  = false
theme.tabbar_radius = 0          
theme.tabbar_style = "modern"   
theme.tabbar_font = "Ubuntu Mono 10"  
theme.tabbar_size = 20 
theme.tabbar_position = "top" 
theme.tabbar_bg_normal = "#000000" 
theme.tabbar_fg_normal = "#ffffff" 
theme.tabbar_bg_focus  = "#1A2026" 
theme.tabbar_fg_focus  = "#ff0000" 
theme.tabbar_disable = false  
theme.tabbar_color_close = "#f9929b"        
theme.tabbar_color_min   = "#fbdf90"        
theme.tabbar_color_float = "#ccaced"  
```
And tabbed layout in my rc.lua
```
awful.layout.layouts = {
    l.tile,
    l.floating,
    l.spiral,
    bling.layout.mstab,
    lain.layout.termfair,
    ll.right,
    ll.left,
    ll.bottom, 
    ll.top,
}
```
![image](https://user-images.githubusercontent.com/44820142/131679268-df28b5b3-d0b6-4058-9e46-e44ca2695a5f.png)

[Full Config](https://github.com/M1ndo/dotfiles/blob/master/.config/awesome/themes/fallen_rainbow/theme.lua)

**Comment by Nooo37** [comment]
I think you are requiring bling before your theme: You have made sure to place `local bling = require("lib.bling")` right under `beautiful.init` in your `rc.lua` but before that you are already requiring your `scratchpad.lua` file that itself requires bling. Try moving the scratchpad require down and let us know if it worked.

**Comment by M1ndo** [comment]
@Nooo37 Indeed it worked , i invoked ```beautiful.init``` twice that's why it didn't work .
Thanks Alot :+1:

**Comment by Nooo37** [comment]
Epic! Also thanks for including the config right away. Way better than having to guess what might cause the problem
