### ISSUE TITLE
Add a bg color to the selected tab in a client when it isn't focused

### ISSUE THREAD

**Issue by tosuki** [BlingCorp/bling#112]
I think it would be really nice if there is a way to make the selected tab has a color when the client isn't focused, for example:

**When the client isn't selected:**
![image](https://user-images.githubusercontent.com/54871261/133487157-36fb20ac-add5-435a-bcd9-554ce41f1c51.png)

**When the client is focused:**
![image](https://user-images.githubusercontent.com/54871261/133487500-407e30d4-03bb-486e-9382-3abeb59ec669.png)

**Comment by Nooo37** [comment]
Valid and great request. Considering the current theme vars are called `tabbar_fg_focus` and `tabbar_fg_normal`, would that one just be called `tabbar_fg_unselected`? I can't come up with an intuitive name for that.

**Comment by okaabe** [comment]
You are right, the name could be `tabbar_bg_focused_inactive` or just `tabbar_bg_inactive`, what do you think about these names?

**Comment by HeavyRain266** [comment]
@okaabe Don't close Issues until referenced PR isn't merged or closed.

**Comment by Nooo37** [comment]
Yea I think while we are at it, we can add the same variables for unfocused (and inactive) tabs. Otherwise it would be a little weird to only have that ability for focused tabs I think (ie probably `tabbar_bg_focused_inactive` and `tabbar_bg_normal_inactive` etc)
