### ISSUE TITLE
Wallpaper module does not work with multiple monitors

### ISSUE THREAD

**Issue by anihm136** [BlingCorp/bling#124]
Currently, the wallpaper module does not work well with multiple monitors. The main reason for this is the function that handles both wallpaper requests from awesome, as well as the timer expirations. This causes alteration of global state, and calling `setup` multiple times with different screens does not work. Also, it would be nice if we could directly pass in a table of screens (the way `gears` supports) to setup for multiple screens more easily.

**Solution**
I already worked out a fix for myself for the first issue, and I'd be happy to share it if you'd like. I'd also like to work on the second one if you feel it's a useful addition to the module

**Comment by Nooo37** [comment]
Oh, calling the `setup` function twice is indeed not what it was meant to do lol. If your fix is a small one, I wouldn't mind adding minor support for that too tho.

**Comment by JavaCafe01** [comment]
@anihm136 I don't think we need two parameters for `screen`. We can have one parameter, and check if it's an array or not, and deal with it accordingly underneath. @Nooo37 is that fine or do you have any other ideas?
