### ISSUE TITLE
imv doesn't swallowing

### ISSUE THREAD

**Issue by r0g3r0g3r** [BlingCorp/bling#139]
i have the module swallow active, but when i launch imv don't work. i tested it with mpv, timeshift and work fine

**Comment by eylles** [comment]
run xprop and click on the imv window, does it report PID? if not can you check if #140 fixes it?

**Comment by r0g3r0g3r** [comment]
does't report PID

**Comment by eylles** [comment]
welp, then that is a problem with imv and you should open an issue to have them add the PID atom, on the meantime you can use this LD_PRELOAD library https://github.com/deepfire/ld-preload-xcreatewindow-net-wm-pid that forces missbehaving windows to have a PID prop, after you compile that library you can make a wrapper script for imv like this:

```
#!/bin/sh
LD_PRELOAD=/path/to/ld-preload-xcreatewindow.so /full/path/to/imv $@
```

perhaps call it imv and have it inside `~/.local/bin/`

**Comment by Nooo37** [comment]
The window swallowing module depends on the PID xproperty. We won't be able to just add support for windows that don't set that property. I'm unaware of any possibility to map window IDs to process IDs otherwise. If there is one, feel free to share it here.
