### ISSUE TITLE
Window switcher titles

### ISSUE THREAD

**Issue by nikh-str** [BlingCorp/bling#161]
Hi! I have a problem with the titles of the Window Switcher widget, the text doesn't appear at all. I have tried keeping the default theme variables and also changing them (fixing margins, fonts etc) but still the titles do not appear (although there is space indicating that there should be text there).

**Comment by Nooo37** [comment]
Can you send the relevant code snippet? What is your screen resolution, dpi and what font are you using? I could imagine your `theme.font` being to big or something so setting and tinkering around with `theme.window_switcher_name_font` might already be enough to solve that issue

**Comment by Uni-qi** [comment]
My screen has: 
dimensions:    1920x1080 pixels (508x285 millimeters)
 resolution:    96x96 dots per inch

and the relevant code snippet:

```
theme.window_switcher_widget_bg = theme.xbackground -- The bg color of the widget
theme.window_switcher_widget_border_width = 2 -- The border width of the widget
theme.window_switcher_widget_border_radius = 5 -- The border radius of the widget
theme.window_switcher_widget_border_color = theme.xcolor0 -- The border color of the widget
theme.window_switcher_clients_spacing = 15 -- The space between each client item
theme.window_switcher_client_icon_horizontal_spacing = 5 -- The space between client icon and text
theme.window_switcher_client_width = 350 -- The width of one client widget
theme.window_switcher_client_height = 250 -- The height of one client widget
theme.window_switcher_client_margins = 20 -- The margin between the content and the border of the widget
theme.window_switcher_thumbnail_margins = 10 -- The margin between one client thumbnail and the rest of the widget
theme.thumbnail_scale = false -- If set to true, the thumbnails fit policy will be set to "fit" instead of "auto"
theme.window_switcher_name_margins = 10 -- The margin of one clients title to the rest of the widget
theme.window_switcher_name_valign = "center" -- How to vertically align one clients title
theme.window_switcher_name_forced_width = 200 -- The width of one title
theme.window_switcher_name_font = "Hack Nerd Font 9" -- The font of all titles
theme.window_switcher_name_normal_color = theme.xcolor4 -- The color of one title if the client is unfocused
theme.window_switcher_name_focus_color = "#af3a1f" -- The color of one title if the client is focused
theme.window_switcher_icon_valign = "center" -- How to vertically align the one icon
theme.window_switcher_icon_width = 20 
```
I have tried different fonts and values for margins, but it seems that I haven't found the right combination.

**Comment by JavaCafe01** [comment]
Is that the correct identifier for Hack? You can check with `fc-list | grep "Hack"`

**Comment by backlands** [comment]
I was facing the same issue and this library respects the following widget setting:

`theme.tasklist_disable_task_name = true`

Discovered that I had this set somewhere in the theme I was using as a starting point. Changing this to false or commenting out the setting fixed the issue and now task names display in the switcher.
