### ISSUE TITLE
[Scratchpad] Is possible to make scratchpad show on specific screen?

### ISSUE THREAD

**Issue by RMTT** [BlingCorp/bling#167]
Scratchpad is convenient, but it can't specific screen like many other widgets.

**Comment by Nooo37** [comment]
Maybe you can set a normal awesomewm rule for that?

**Comment by Nooo37** [comment]
It seems like you can hook up to the "turn on" signal and set the screen there
```lua
my_scratchpad:connect_signal("turn_on", function(c)
  c.screen = screen[1]
end)
```

**Comment by RMTT** [comment]
Sorry, i have quit awesomewm now, so i cannot verify it. i will close this issue.
