### ISSUE TITLE
`theme.tabbar_{b,f}g_focus_inactive` ignored in mstab layout

### ISSUE THREAD

**Issue by paulbdavis** [BlingCorp/bling#173]
For some reason the `create` function is being called without the `inactive_bool` argument from the `mstab.lua`'s `update_tabbar` function. This is causing it to never render the tabbar as "inactive" so these theme options are never applied, it just stays as though it is focused

I tried patching it into the `mstab.lua` file, but it didn't seem to work, as the `c.bling_tabbed` is never defined here?

```lua
function update_tabbar(
    clients,
    t,
    top_idx,
    area,
    master_area_width,
    slave_area_width
)
    local s = t.screen

    -- create the list of clients for the tabbar
    local clientlist = bar.layout()
    for idx, c in ipairs(clients) do
        -- focus with right click, kill with mid click, minimize with left click
        local buttons = gears.table.join(
            awful.button({}, 1, function()
                c:raise()
                client.focus = c
            end),
            awful.button({}, 2, function()
                c:kill()
            end),
            awful.button({}, 3, function()
                c.minimized = true
            end)
        )

        -- tried to get it here, but c.bling_tabbed is never there
        local inactive = false
        if c.bling_tabbed then
           gears.debug.dump(c, "mstab.update_tabbar:client")
           local tabobj = c.bling_tabbed
           gears.debug.dump(tabojb, "mstab.update_tabbar:tabojb")
           local tabobj_focused_client = tabobj.clients[tabobj.focused_idx]
           local tabobj_is_focused = (client.focus == tabobj_focused_client)
           inactive = not tabobj_is_focused
        end
        local client_box = bar.create(c, (idx == top_idx), buttons, inactive)
        clientlist:add(client_box)
    end

-- the rest I cut out
end

**Comment by paulbdavis** [comment]
Adding this seems to result in the desired behaviour though

```lua
        local inactive = false
        if client.focus == awful.client.getmaster() then
           inactive = true
        end
        local client_box = bar.create(c, (idx == top_idx), buttons, inactive)
        clientlist:add(client_box)
```

**Comment by Nooo37** [comment]
This is our major communication problem: `bling.layout.mstab` != `bling.module.tabbed`. They have nothing to do with each other, neither conceptually nor code wise. The first is a "static" layout with a tabbed groupe of clients on the side. The latter is to create the impression that multiple windows are tabbed like in a browser and can be moved as one groupe etc

**Comment by paulbdavis** [comment]
Yeah, I was seeing that they are not quite the same, just use the same widgets under the hood.

So what would one use the `bling.module.tabbed` to do? Could the `mstab` layout be updated to use the module instead of making the tab on it's own?

**Comment by paulbdavis** [comment]
OK, I now understand. You use the module to make a tab container in any other layout by calling `bling.module.tabbed.pick` or similar on any container. If I get a chance maybe I'll send a PR for the docs to clarify a bit.

**Comment by Nooo37** [comment]
Oh yea almost forgot that they use the same tabbar now. Well then it would of course make sense to also honor the theme variables you named
