### ISSUE TITLE
Scratchpads won't work

### ISSUE THREAD

**Issue by Forgotten-Email** [BlingCorp/bling#176]
Hello,
I'm trying to setup scratchpads so i could get a dropdown terminal on any tag without switching to my terminal tag, which I have set my terminal to always open on. I tried copying the example, swapping out wezterm for kitty:

```lua
local bling = require("modules.bling")

local term_scratch = bling.module.scratchpad {
    command = "kitty --class=spad",                   -- How to spawn the scratchpad
    rule = { instance = "spad" },                     -- The rule that the scratchpad will be searched by
    sticky = true,                                    -- Whether the scratchpad should be sticky
    autoclose = true,                                 -- Whether it should hide itself when losing focus
    floating = true,                                  -- Whether it should be floating (MUST BE TRUE FOR ANIMATIONS)
    geometry = {x=0, y=0, height=300, width=1366}, -- The geometry in a floating state
    reapply = true,                                   -- Whether all those properties should be reapplied on every new opening of the scratchpad (MUST BE TRUE FOR ANIMATIONS)
    dont_focus_before_close  = false,                 -- When set to true, the scratchpad will be closed by the toggle function regardless of whether its focused or not. When set to false, the toggle function will first bring the scratchpad into focus and only close it on a second call
}
```
And then toggling the scratchpad with a keybind:
```lua
awful.keyboard.append_global_keybinding({
  awful.key({ modkey, "Shift"}, "Return", function() term_scratch:toggle() end,
    {description = "Toggle Drop-Down Terminal", group = "Applications"}),
})
```
But the scratchpad won't open. I've tried with other terminals but it wont work for me, and I'm not sure why.
Thanks in advance for any help.

**Comment by Nooo37** [comment]
Is there any error in stdout?

**Comment by Forgotten-Email** [comment]
> Is there any error in stdout?

How would I capture the stdout for the module?

**Comment by JavaCafe01** [comment]
@Forgotten-Email When I try your code what breaks is the keybind portion. Your actual scratchpad works fine.

**Comment by Forgotten-Email** [comment]
> @Forgotten-Email found the issue.
> 
> In AwesomeWM there is `awful.keyboard.append_global_keybinding` and `awful.keyboard.append_global_keybindings`. Because you are using a table of key(s), you need the latter.

That worked, I’m surprised I didn’t realise that before. Thanks for the help :D
