### ISSUE TITLE
require error in helpers

### ISSUE THREAD

**Issue by necreativny** [BlingCorp/bling#180]
im getting `error: /usr/share/awesome/lib/awful/client/shape.lua:67: attempt to call local '_shape' (a table value)` when i import blink.
this error gets away if i comment **shape** import in **helpers**
```
-- ..bling/helpers/init.lua

return {
    client = require(... .. ".client"),
    color = require(... .. ".color"),
    filesystem = require(... .. ".filesystem"),
    -- shape = require(... .. ".shape"),
    time = require(... .. ".time"),
}

```

**Comment by Nooo37** [comment]
That's weird. Can you post your rc.lua? What if you added `local` in the `bling/helpers/shape.lua` file? Maybe something is colliding there, there is no reason it shouldn't be local
```diff
-shape = {}
+local shape = {}
```

**Comment by necreativny** [comment]
ahh, right! i declared 'shape' in my global rc.lua, adding `local` it is imported properly
