### ISSUE TITLE
[Tag/Task]List Preview support dual monitor?

### ISSUE THREAD

**Issue by AdsonCicilioti** [BlingCorp/bling#183]
How i could make the preview appear on respective screen where is triggered?

The example on documentation cover only setups with one screen.

#### Actual behavior

When the cursor is hover on the task or tags of any screen, the preview is displayed on the screen from the left.

**Comment by AdsonCicilioti** [comment]
I achieve work correctly, adding - `parent = awful.screen.focused` - at args of  placement_fn method.

Maybe this could at on documentation. Will be helpful!

**Comment by Nooo37** [comment]
Yea that that is also possible through the placement_fn argument would be a good extra example/comment in the documentation
