### ISSUE TITLE
Flash focus dual monitor not flash

### ISSUE THREAD

**Issue by AgusAzar** [BlingCorp/bling#186]
When moving to a client that is the only one in that screen doesn't flahs

**Comment by Nooo37** [comment]
Yes that is explicit in the code ([here](https://github.com/BlingCorp/bling/blob/e6de047ced41051236a390b081105f598cb0ad8b/module/flash_focus.lua)). If it bothers you, feel free to copy/paste the small file and make adjustments. Bling isn't the single source of truth. I don't think we should add yet another beautiful configuration variable for that as there are already way too many
