### ISSUE TITLE
[Feature Request] Navigate in tabbed containers via index numbers?

### ISSUE THREAD

**Issue by Horuyuki** [BlingCorp/bling#201]
A simple if statement has no way to determine when to invoke the `.iter()` function versus the `.focus.byidx()` function since there is no way to tell when the iteration reached the end and jumped back to the beginning.

Am I missing a feature provided by bling that can let me switch focus by using two keybindings to go back and forth between all clients, whether tabbed or not? I would like a shortcut to be able to iterate through the tabs in a slave container and return to the master container once it reached the end.

**Comment by Nooo37** [comment]
Are you referring to `bling.module.tabbed` or to `bling.layout.mstab`?

**Comment by Horuyuki** [comment]
I am referring to tabbed, but I moved to dwm shortly after, so I will close this request for now.
