### ISSUE TITLE
Windows opened with scratchpad becomes black for seconds

### ISSUE THREAD

**Issue by branwright1** [BlingCorp/bling#44]
That's really weird since everytime when I saw people using this module there wasn't any problems but I have tried it on my laptop with intel gpu and VM on macbook pro with intel and amd, same problems on both when you use intel gpu, doesn't matter if I'm running compositor or not.  Also just noticed that sometimes scratch window "lost focus state" then it is opened multipe times and cannot be focused. :thinking:

It just might be problem from Xorg site since we move windows outside of visible are then they are not rendered at all and server need to render window content when they appears. those animations aren't from compositor so server becomes dumb when window is animated and have too small amout of time to render content before window get selected position.

Example vid below:
https://imgur.com/a/fYtIs91

**Comment by JavaCafe01** [comment]
Any others getting this problem? @Nooo37

**Comment by JavaCafe01** [comment]
I can confirm this is a nixos only problem @branwright1

**Comment by branwright1** [comment]
> I can confirm this is a nixos only problem @branwright1

I think it's something with mesa or intel drivers or intel in general because I can't even update microcode but tried it with AMD APU and works fine

**Comment by JavaCafe01** [comment]
> > I can confirm this is a nixos only problem @branwright1
> 
> I think it's something with mesa or intel drivers or intel in general because I can't even update microcode but tried it with AMD APU and works fine

I'll try running with solely nvidia and check

**Comment by branwright1** [comment]
Closing because it's problem with intel gpu drivers not bling.

**Comment by M1ndo** [comment]
@HeavyRain266 I Kinda have a similar issue , when toggling a new scratch it does open with focus on and when it losses focus it does autoclose like it should , however when toggling it back it spawns a new scratch instead of bringing it back .
