### ISSUE TITLE
Typo in the documentation

### ISSUE THREAD

**Issue by DeBeast591** [BlingCorp/bling#56]
I found a little typo in the documentation while reading up on it.

Here's the file: `https://github.com/BlingCorp/bling/blob/master/docs/module/wall.md`

The line (`set_function = bling.module...`) should have a `,` at the end of the line.
```Lua
-- A random wallpaper with images from multiple folders
bling.module.wallpaper.setup {
    set_function = bling.module.wallpaper.setters.random
    wallpaper = {"/path/to/a/folder", "/path/to/another/folder"},
    change_timer = 631,  -- prime numbers are better for timers
    position = "fit",
    background = "#424242"
}
```

Just thought I would point this out so it could be fixed.

**Comment by JavaCafe01** [comment]
Fixed! Thanks :+1:
