### ISSUE TITLE
[tabbar] - Translate existing client's titlebar to each tab

### ISSUE THREAD

**Issue by Piterden** [BlingCorp/bling#57]
I think it would be the correct way to inherit config of each tab from existing config of client titlebar.

Mouse bindings (move, resize) now are not working on tabgroups clients, it is useless thing.

Any thoughts?

**Comment by Nooo37** [comment]
We can't just inherit from an existing titlebar config. At least I wouldn't know how to do so. If you depend on your titlebars mouse bindings, you can move the tabbar to the bottom side (or to the left or the right side with the `boxes` style). We could however add mouse bindings for moving and resizing a tabgroup. Maybe adding buttons to the titlebar widget in the `update_tabbar` function would already be enough for that.

**Comment by Nooo37** [comment]
It should nowadays be possible to "inherit from an existing titlebar config" through the [tabbed misc module](https://blingcorp.github.io/bling/#/widgets/tabbed_misc?id=titlebar-indicator) for those that want more elaborate tabbars
