### ISSUE TITLE
question about Tag_preview widget

### ISSUE THREAD

**Issue by actionless** [BlingCorp/bling#64]
I recently forked tag_preview widget to work in a similar way as popular awesome extension "Revelation"

![2021-06-09--1623241094_1920x1080_scrot](https://user-images.githubusercontent.com/1655669/121352857-8f4f9200-c92d-11eb-8270-35189a297c9d.png)

I wonder if you interested in continue on working on this direction of that widget as a separate project or not.

**Comment by actionless** [comment]
the source could be found here: https://github.com/actionless/awesome_config/blob/master/actionless/tag_previewz.lua

**Comment by JavaCafe01** [comment]
@actionless that's amazing! To answer your question, it really depends on how much of the widget is related to the original bling tag_preview. As of now, I'd prefer if it was a separate widget in bling, but I am also ok with it if you want to start this as a separate project.

**Comment by actionless** [comment]
i mean, if you interested to collaborate on improving it the direction shown on a screenshot i can make a separate repo for it, otherwise i'll just leave it as a part of the config

**Comment by JavaCafe01** [comment]
Ah I see what you mean. Sure, I'm interested in making a separate repo for it!

**Comment by actionless** [comment]
more ideas:
1) displaying tag indices
2) keyboard navigation same as in Revelation
3) dynamic tagging features:
     3.1) add/remove tag
     3.2) "protect" first N tag indices from being removed
4) [not interested myself but someone could find useful] drag-n-dropping clients from tag to tag

**Comment by actionless** [comment]
7(?) btw, subscribing to client.name and client.icon changes would allow to recreate Windows™ Tiles™ but the right way :D

**Comment by JavaCafe01** [comment]
@actionless Sorry for the late response, I was finishing up exams last week. Those all seem like good ideas! I have interest in all of them except 5 and 7. How shall we proceed with the separate repository?

**Comment by actionless** [comment]
good to hear, let's just choose repo name and location then

speaking of name, i was thinking of 'tag(s?) overview'

**Comment by JavaCafe01** [comment]
@actionless Maybe Awesome Overview? I'm really bad at names :laughing:

As for the repo location, would you like to keep it under the BlingCorp org?

**Comment by JavaCafe01** [comment]
Also would you like to move this discussion somewhere else? Like Matrix, or Discord?

**Comment by actionless** [comment]
> Awesome Overview?

also good option

> would you like to keep it under the BlingCorp org?

i dont mind/care much

for private messages i prefer e-mail over messengers

**Comment by JavaCafe01** [comment]
@actionless, I just created a new repository [here](https://github.com/BlingCorp/awesome-overview) and invited you. We can continue our discussion as an issue over there, or by using the new discussions feature.

**Comment by actionless** [comment]
thanks!

**Comment by actionless** [comment]
i gonna push the code in a week or so after somewhat cleaning up some debugging things and inlining deps on some internal modules of my config

**Comment by JavaCafe01** [comment]
Hey @actionless its been a week and you might be busy, but I'm just pinging you to check up on how everything is going. If you're too busy I can grab your code and push it to the repo!

**Comment by actionless** [comment]
yup, couple of days ago i've removed all extra deps (https://github.com/actionless/awesome_config/commits/master/actionless/tag_previewz.lua), i think it's time indeed to push it :)

**Comment by JavaCafe01** [comment]
@actionless That's great to hear! I'm planning to do a reddit post soon with all of BlingCorps AwesomeWM stuff to hopefully attract more users, and adding in Awesome-Overview would be pretty cool

**Comment by actionless** [comment]
the code is more or less ready for 'beta test' users as in its current state1, but it's totally missing any readme, and im not good in such sort of stuff

**Comment by actionless** [comment]
also it seems you've got the permissions wrong on the repo

**Comment by JavaCafe01** [comment]
@actionless I did send you an invite to be maintainer for the [`awesome-overview`](https://github.com/BlingCorp/awesome-overview) repo, but it's still pending. I canceled it and sent the invite again.

**Comment by actionless** [comment]
weird, i remember i was accepting it, but mb i did it in the same minute of its expiration (it expires in one week) so it turned the system crazy or smth like that :D 

anyway now ive pushed the working version
