### ISSUE TITLE
Deck Layout

### ISSUE THREAD

**Issue by JavaCafe01** [BlingCorp/bling#68]
This was featured on river recently, and I would like to see it implemented for AwesomeWM. Here's an example from `snakedye` on the r/unixporn discord:

![image](https://user-images.githubusercontent.com/33443763/121957916-ea133000-cd17-11eb-877b-fa6e25c102e1.png)

The clients get stacked as shown, and displayed like a deck of cards.

**Comment by undefinedDarkness** [comment]
that does look epic
