### ISSUE TITLE
Cleanup license

### ISSUE THREAD

**Issue by HeavyRain266** [BlingCorp/bling#69]
Hey, instead of adding new names to licenses, I would recommend something similiar to what [river](https://github.com/ifreund/river) provide. 
License provide name of maintainer, which in this case would be BlingCorp, and additional file [authors](https://github.com/ifreund/river/blob/master/AUTHORS) which provide names of people which contributed bigger changes.

In my opinion it makes more sense since bling was moved from personal repo into organization.

**Comment by JavaCafe01** [comment]
@Nooo37 ?

**Comment by Nooo37** [comment]
Cute idea. I would be fine with that

**Comment by JavaCafe01** [comment]
Done.
