### ISSUE TITLE
Can't iterate through tabs in mstab layout

### ISSUE THREAD

**Issue by vinicius507** [BlingCorp/bling#73]
Greetings,

When in `mstab` layout I seem to be unable to iterate through tabs using `bling.module.tabbed.iter()`.

Here are my keybindings:
```lua
	-- Mstab
	awful.key({ _G.superkey }, '+',
		function ()
			bling.module.tabbed.iter(1)
		end,
		{ description = 'focus next tab', group = 'mstab layout' }
	),

	awful.key({ _G.superkey }, '-',
		function ()
			bling.module.tabbed.iter(-1)
		end,
		{ description = 'focus previous tab', group = 'mstab layout' }
	),

```
Any help would be appreciated. Thanks.

**Comment by Nooo37** [comment]
`mstab` is a dynamic layout - not different from your default `tile` layout. You iterate through it by for example mod+tabbing (in the default config at least). The `bling.module.tabbed` function are needed for the tabbed module which creates tabbing groups regardless of your current dynamic layout. Hope that made sense. There sure is some confusion with two tabbing features :sweat_smile:

**Comment by Nooo37** [comment]
@vinicius507 Do you still have that problem? #59 has been the same misconception I think.

**Comment by vinicius507** [comment]
Actually no! Thanks for the help and the reminder though!
